[build]
  publish = "build" # The folder where your production build is located
  command = "npm run build" # The build command to create the production build

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 
